language:
  elixir

env:
  global:
    - MIX_ENV=test

matrix:
  include:
    - otp_release: 20.2
      elixir: 1.6.4

jobs:
  include:
    - stage: test
      script:
        # Run the tests
        - mix compile
        - mix do credo --strict, format --check-formatted --dry-run
        - mix coveralls.travis

    - stage: git tag
      script:
        # Tag the release
        - echo "tag the release here"

    - stage: hex publish
      script:
        # Publish to the hex package manager
        - echo "publish script here"

